Design decision for storage API entry points on the bucket object
WICG/storage-buckets pull request #13
Opened 2020-09-30 22:59 UTC by ayuishii

Resolve TODO in [Bucket designation for each storage API](https://github.com/WICG/storage-buckets/blob/gh-pages/explainer.md#bucket-designations-for-each-storage-api) section.

2020-10-20 02:20 UTC, pwnall requested changes
Thank you for describing how this alternative plays out!

2020-10-20 02:20 UTC, pwnall commented on explainer.md
> +Having entry points to for each storage API on the bucket also makes replacing
"to for" -> "to" ?

2020-10-20 02:20 UTC, pwnall commented on explainer.md
> +Web developers will have to specify bucket names in the options per storage API
"will have" -> "would have"?

2020-10-20 02:20 UTC, pwnall commented on explainer.md
> +creating more opportunity for error by either forgetting to specify a name
opportunity -> opportunities
error -> errors

2020-10-20 02:20 UTC, pwnall commented on explainer.md
> +or typos in the bucket name.
or typos -> or having typos?

(Parallel structure -- the other element in the list is "forgetting ...", which is a verb.)

2020-10-20 02:20 UTC, pwnall commented on explainer.md
> +window.indexedDB = inboxBucket.indexedDB;
Please wire a couple more entry points and then have a `// ...` comment.

```js
window.caches = inboxBucket.caches;
navigator.storage.estimate = inboxBucket.estimate.bind(inboxBucket);
// ...
```

2020-10-20 18:13 UTC, ayuishii commented
Thanks for reviewing!

2020-10-21 04:23 UTC, pwnall approved these changes
LGTM, thank you for the revisions!

2020-10-21 04:23 UTC, merged